const $=s=>document.querySelector(s);
const icons={Dnes:"🏠",Cíle:"🎯",Kvadranty:"⊞",Život:"👤",Nastavení:"⚙️"};
let state=JSON.parse(localStorage.getItem("priorityLife")||"null")||{
 view:"Dnes",
 goals:[
 {name:"Být finančně nezávislý",area:"Finance",progress:60,horizon:"10 let"},
 {name:"Udržet si zdraví a energii",area:"Zdraví",progress:80,horizon:"10 let"},
 {name:"Silné vztahy s rodinou",area:"Vztahy",progress:75,horizon:"10 let"},
 {name:"Každý den se posouvat",area:"Rozvoj",progress:55,horizon:"10 let"}],
 tasks:[
 {name:"Zavolat 5 klientům",area:"Finance",imp:10,urg:5,mins:45,done:false},
 {name:"Pohyb / trénink",area:"Zdraví",imp:9,urg:3,mins:45,done:false},
 {name:"Čas s rodinou",area:"Vztahy",imp:9,urg:2,mins:60,done:false},
 {name:"Studium / rozvoj",area:"Rozvoj",imp:8,urg:2,mins:30,done:false}],
 review:null,
 goalHorizon:"10 let"
};
const save=()=>localStorage.setItem("priorityLife",JSON.stringify(state));
const areaIcon=a=>({Zdraví:"❤️",Finance:"🪙",Vztahy:"👥",Rozvoj:"🧠"}[a]||"🎯");
const quad=t=>t.imp>=6?(t.urg>=6?1:2):(t.urg>=6?3:4);
const navs=["Dnes","Cíle","Kvadranty","Život","Nastavení"];
function navHTML(){return navs.map(n=>'<button class="'+(state.view===n?'active':'')+'" onclick="go(\''+n+'\')"><span>'+icons[n]+'</span>'+n+'</button>').join("")}
function go(v){state.view=v;save();render()}
function openAdd(){ $("#taskGoal").innerHTML=state.goals.map(g=>'<option>'+g.name+'</option>').join("");$("#modal").classList.add("show")}
function closeModal(){$("#modal").classList.remove("show")}
function saveTask(){let name=$("#taskName").value.trim();if(!name)return;state.tasks.push({name,area:$("#taskArea").value,imp:+$("#importance").value,urg:+$("#urgency").value,mins:30,done:false});save();closeModal();render()}
function done(i){state.tasks[i].done=!state.tasks[i].done;save();render()}
function areas(){
 const vals={Zdraví:88,Finance:76,Vztahy:91,Rozvoj:64};
 return Object.entries(vals).map(([a,v])=>'<div class="area"><b>'+areaIcon(a)+'</b><div><div>'+a+'</div><div class="bar '+(v<75?'warn':'')+'"><i style="width:'+v+'%"></i></div></div><b>'+v+'%</b></div>').join("")
}
function priorities(){return state.tasks.filter(t=>!t.done).sort((a,b)=>(b.imp*3+b.urg)-(a.imp*3+a.urg)).slice(0,3).map((t,k)=>'<div class="priority"><span class="num">'+(k+1)+'</span><div style="flex:1"><b>'+areaIcon(t.area)+' '+t.name+'</b><small style="display:block">'+t.mins+' min • Q'+quad(t)+'</small></div><button onclick="done('+state.tasks.indexOf(t)+')" class="icon" style="width:32px;height:32px;font-size:15px">✓</button></div>').join("")}
function dashboard(){return '<div class="grid dashboard"><div class="card hero"><h3>🚦 Životní semafor</h3><div class="score"><b>82<small>/ 100</small></b></div><p style="text-align:center" class="green"><b>Jdeš správným směrem.</b></p><div class="quote" id="quoteBox">„Nejdřív buduj. Potom nebudeš muset hasit.“</div></div><div class="card"><h3>Moje životní oblasti</h3><div class="areas">'+areas()+'</div><hr style="border:0;border-top:1px solid #edf1f5;margin:18px 0"><h3>🎯 3 priority pro dnešek</h3>'+priorities()+'<button class="primary full" style="margin-top:14px" onclick="showNow()">Co je teď nejdůležitější?</button></div><div class="motivation"><blockquote>„Velké výsledky vznikají z malých kroků, které děláš opakovaně.“</blockquote><small>Dnešní motivace</small></div></div>'}
function editGoal(i){state.editGoalIndex=i;state.view="Nastavení";save();render()}
function legacyEditGoal(i){const g=state.goals[i];const name=prompt("Název cíle:",g.name);if(name===null)return;const area=prompt("Oblast (Zdraví, Finance, Vztahy, Rozvoj):",g.area);if(area===null)return;const horizon=prompt("Horizont (10 let, 5 let, 1 rok, Měsíc):",g.horizon);if(horizon===null)return;const p=prompt("Splněno v % (0–100):",g.progress);if(p===null)return;g.name=name.trim()||g.name;g.area=area.trim()||g.area;g.horizon=horizon.trim()||g.horizon;g.progress=Math.max(0,Math.min(100,Number(p)||0));save();render()}
function deleteGoal(i){if(confirm("Opravdu smazat tento cíl?")){state.goals.splice(i,1);save();render()}}
function addGoal(){const name=prompt("Napiš nový cíl:");if(!name||!name.trim())return;const area=prompt("Oblast (Zdraví, Finance, Vztahy, Rozvoj):","Rozvoj")||"Rozvoj";const horizon=prompt("Horizont (10 let, 5 let, 1 rok, Měsíc):","1 rok")||"1 rok";state.goals.push({name:name.trim(),area:area.trim(),progress:0,horizon:horizon.trim()});save();render()}
function setGoalHorizon(h){state.goalHorizon=h;save();render()}
function goals(){const h=state.goalHorizon||"10 let";return '<div class="grid two"><div class="card"><div class="tabs">'+["10 let","5 let","1 rok","Měsíc"].map(x=>'<button class="'+(h===x?'active':'')+'" onclick="setGoalHorizon(\''+x+'\')">'+x+'</button>').join("")+'</div><h2>Moje cíle</h2>'+state.goals.filter(g=>g.horizon===h).map(g=>({g,i:state.goals.indexOf(g)})).map(({g,i})=>'<div class="goal"><div class="goalTop"><b>'+areaIcon(g.area)+' '+g.name+'</b><b>'+g.progress+'%</b></div><small class="muted">'+g.area+' • '+g.horizon+'</small><div class="bar '+(g.progress<60?'warn':'')+'" style="margin-top:8px"><i style="width:'+g.progress+'%"></i></div><div class="goalActions"><button onclick="editGoal('+i+')">✏️ Upravit</button><button class="dangerBtn" onclick="deleteGoal('+i+')">🗑 Smazat</button></div></div>').join("")+'<button class="primary" style="margin-top:16px" onclick="addGoal()">＋ Přidat cíl</button></div><div class="motivation"><blockquote>„Směr je důležitější než rychlost.“</blockquote><small>Každý cíl začíná rozhodnutím.</small></div></div>'}
function quadrants(){let desc={1:["Důležité a naléhavé","Krize • termíny • neodkladné problémy"],2:["Důležité a nenaléhavé","Prevence • vztahy • plánování • zdraví"],3:["Nedůležité a naléhavé","Vyrušení • některé hovory • požadavky"],4:["Nedůležité a nenaléhavé","Zbytečnosti • bezcílné brouzdání"]};return '<div class="quadrants">'+[1,2,3,4].map(q=>'<div class="q q'+q+'"><h2>Q'+q+'</h2><b>'+desc[q][0]+'</b><p><small>'+desc[q][1]+'</small></p>'+state.tasks.filter(t=>quad(t)===q).map(t=>'<div class="taskchip">'+areaIcon(t.area)+' '+t.name+'</div>').join("")+'</div>').join("")+'</div><div class="card" style="margin-top:14px"><b>🌱 Hlavní pozornost: Q2</b><p class="muted">Věnuj čas důležitým věcem dříve, než se stanou krizí.</p><button class="primary" onclick="openAdd()">＋ Přidat činnost</button></div>'}
function stats(){return '<div class="grid two"><div class="card"><h2>Statistiky</h2><div class="tabs"><button class="active">Týden</button><button>Měsíc</button><button>Rok</button></div><div class="statbig"><div class="donut"></div><div><p>Q1 — 17 %</p><p class="green"><b>Q2 — 61 %</b></p><p>Q3 — 14 %</p><p>Q4 — 8 %</p></div></div><h3 style="margin-top:24px">Trend Q2</h3><div class="bar" style="height:14px"><i style="width:61%"></i></div><p class="muted">41 → 47 → 52 → 55 → 61 % 📈</p><div class="metrics"><div class="metric"><span>🌿 Proaktivita</span><br><b class="green">78%</b></div><div class="metric"><span>🔥 Reaktivita</span><br><b class="red">22%</b></div></div></div><div class="card"><h3>Další ukazatele</h3><p>✓ Splněné aktivity <b>24 / 32</b></p><p>◎ Dokončené cíle <b>3 / 5</b></p><p>◷ Odložené důležité úkoly <b>4</b></p><p>↗ Přešly z Q2 do Q1 <b>2</b></p><hr style="border:0;border-top:1px solid #edf1f5"><p><b>Směr:</b> více času v Q2, méně hašení krizí.</p></div></div>'}
function life(){return '<div class="grid two"><div class="card"><h2>🧭 Můj život</h2><p class="muted">Od vize k dnešním krokům.</p><div class="motivation"><blockquote>„Žít zdravý, svobodný a naplněný život. Být oporou pro svou rodinu a dělat smysluplnou práci.“</blockquote><small>Moje vize</small></div><h3 style="margin-top:18px">Životní oblasti</h3>'+areas()+'</div><div class="card"><h3>🌙 Večerní vyhodnocení</h3><div class="review"><p>Jaký byl dnešní den?</p><div class="rate">😞 <span>1</span><span>2</span><span>3</span><span>4</span><span>5</span><span>6</span><span>7</span><span>8</span><span>9</span> 😄</div><label>Co se dnes povedlo?</label><textarea id="win" placeholder="Např. trénink, důležitý rozhovor…"></textarea><label>Co mi zbytečně bralo čas?</label><textarea id="waste" placeholder="Např. sociální sítě, neplánované hovory…"></textarea><label>Co je nejdůležitější zítra?</label><textarea id="tomorrow" placeholder="Jedna opravdu důležitá věc…"></textarea><button class="primary full" onclick="saveReview()">Uložit den</button></div></div></div>'}
function settings(){let i=Number.isInteger(state.editGoalIndex)?state.editGoalIndex:0;let g=state.goals[i]||state.goals[0];if(!g)return '<div class="card"><h2>⚙️ Nastavení</h2><p>Zatím nemáš žádný cíl.</p></div>';return '<div class="card settingsCard"><h2>⚙️ Nastavení cíle</h2><p class="muted">Tady můžeš cíl kompletně upravit.</p><label>Název cíle<input id="setGoalName" value="'+g.name.replaceAll('"','&quot;')+'"></label><label>Oblast<select id="setGoalArea">'+["Zdraví","Finance","Vztahy","Rozvoj"].map(a=>'<option '+(a===g.area?'selected':'')+'>'+a+'</option>').join("")+'</select></label><label>Časový horizont<select id="setGoalHorizon">'+["10 let","5 let","1 rok","Měsíc"].map(h=>'<option '+(h===g.horizon?'selected':'')+'>'+h+'</option>').join("")+'</select></label><label>Splnění cíle <b id="setGoalProgressOut">'+g.progress+'%</b><input id="setGoalProgress" type="range" min="0" max="100" value="'+g.progress+'" oninput="setGoalProgressOut.textContent=this.value+\'%\'"></label><div class="settingsActions"><button class="primary" onclick="saveGoalSettings('+i+')">💾 Uložit změny</button><button class="dangerBtn" onclick="deleteGoal('+i+')">🗑 Smazat cíl</button></div></div>'}
function saveGoalSettings(i){let g=state.goals[i];if(!g)return;g.name=$("#setGoalName").value.trim()||g.name;g.area=$("#setGoalArea").value;g.horizon=$("#setGoalHorizon").value;g.progress=+$("#setGoalProgress").value;state.goalHorizon=g.horizon;save();go("Cíle")}
function saveReview(){state.review={win:$("#win").value,waste:$("#waste").value,tomorrow:$("#tomorrow").value,date:new Date().toISOString()};save();alert("Den uložen ✓")}
function showNow(){let t=state.tasks.filter(x=>!x.done).sort((a,b)=>((b.imp*3+b.urg)+(quad(b)==2?8:0))-((a.imp*3+a.urg)+(quad(a)==2?8:0)))[0];if(!t)return alert("Všechny priority jsou hotové 🎉");$("#pageTitle").textContent="Co je teď nejdůležitější?";$("#view").innerHTML='<div class="card focus"><div class="rocket">🚀</div><p class="badge">DOPORUČENÁ AKTIVITA</p><h2>'+areaIcon(t.area)+' '+t.name+'</h2><p><span class="badge">Q'+quad(t)+'</span> &nbsp; ⏱ '+t.mins+' minut</p><h3>Proč právě toto?</h3><p>✓ Vysoká důležitost pro tvé cíle<br>✓ '+(quad(t)==2?'Je důležité, ale zatím neurgentní<br>✓ Chráníš tím svůj Q2 a budoucnost':'Má vysokou aktuální prioritu')+'</p><button class="primary" onclick="startFocus(\''+t.name.replaceAll("'","\\'")+'\','+t.mins+')">▶ Začít</button><br><button style="border:0;background:none;color:#0877e8;margin-top:18px" onclick="go(\'Dnes\')">Zvolit jinou prioritu</button></div>'}
function startFocus(name,mins){let end=Date.now()+mins*60000;$("#view").innerHTML='<div class="card focus"><div class="rocket">🎯</div><p>PRÁVĚ TEĎ DĚLÁM</p><h2>'+name+'</h2><div id="timer" style="font-size:48px;font-weight:800">'+mins+':00</div><p class="muted">Teď existuje jen jedna důležitá věc.</p><button class="primary" onclick="go(\'Dnes\')">✓ Hotovo</button></div>';let x=setInterval(()=>{let d=Math.max(0,end-Date.now()),m=Math.floor(d/60000),s=Math.floor(d%60000/1000),el=$("#timer");if(!el){clearInterval(x);return}el.textContent=m+':'+String(s).padStart(2,"0");if(!d)clearInterval(x)},1000)}
function render(){let titles={Dnes:"Dnes",Cíle:"Moje vize a cíle",Kvadranty:"Coveyho kvadranty",Život:"Můj život",Nastavení:"Nastavení"};$("#pageTitle").textContent=titles[state.view];$("#today").textContent=new Intl.DateTimeFormat("cs-CZ",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(new Date());$("#desktopNav").innerHTML=navHTML();$("#mobileNav").innerHTML=navHTML();$("#view").innerHTML=state.view==="Dnes"?dashboard():state.view==="Cíle"?goals():state.view==="Kvadranty"?quadrants():state.view==="Život"?life():settings()}
render();
const quotes=["„Nejdřív buduj. Potom nebudeš muset hasit.“","„Není cílem stihnout všechno. Cílem je nezanedbat to důležité.“","„Malý krok dnes může změnit směr zítřka.“","„Směr je důležitější než rychlost.“"];
setInterval(()=>{let q=$("#quoteBox");if(q)q.textContent=quotes[Math.floor(Date.now()/8000)%quotes.length]},8000);